import { ROLES } from './roles';

export const PERMISSIONS = {
  // Common
  DASHBOARD: [ROLES.MANAGER, ROLES.DRIVER, ROLES.SAFETY, ROLES.ANALYST],
  
  // Specific
  VEHICLES: [ROLES.MANAGER, ROLES.SAFETY], // Safety might need to see vehicles for inspection
  DRIVERS: [ROLES.MANAGER, ROLES.SAFETY], // Safety might view driver safety scores
  TRIPS: [ROLES.MANAGER, ROLES.DRIVER, ROLES.SAFETY],
  MAINTENANCE: [ROLES.MANAGER, ROLES.SAFETY],
  FINANCE: [ROLES.MANAGER, ROLES.ANALYST],
  REPORTS: [ROLES.MANAGER, ROLES.ANALYST, ROLES.SAFETY],
  
  // Driver specific
  MY_TRIPS: [ROLES.DRIVER],
  VEHICLE_INFO: [ROLES.DRIVER],
  TRIP_HISTORY: [ROLES.DRIVER],
  PROFILE: [ROLES.DRIVER],
  
  // Safety specific
  INSPECTIONS: [ROLES.SAFETY],
  SAFETY_REPORTS: [ROLES.SAFETY],
  
  // Analyst specific
  EXPENSES: [ROLES.ANALYST],
  ANALYTICS: [ROLES.ANALYST],
};
